---
apiVersion: v1
kind: Service
metadata:
  name: apple-service
  labels:
    managedby: HimT
    app: apple.com
    env: Stage
spec:
  type: NodePort
  selector:
    managedby: HimT
    app: apple.com
    env: Stage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
