apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple.inc
  labels:
    managedby: HimT
    app: apple.com
    env: Stage
spec:
  replicas: 2
  selector:
    matchLabels:
      managedby: HimT
      app: apple.com
      env: Stage
  template:
    metadata:
      name: uk-site
      labels:
        managedby: HimT
        app: apple.com
        env: Stage
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apple-html
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: apple-html
          configMap:
            name: apple-html
